env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
plugins:
  - '@typescript-eslint'
rules: {
  linebreak-style: 'off',
  no-console: 'off',
  no-duplicate-imports: 'warn',
  import/extensions: ['error', 'never'],
  class-methods-use-this: 'off',
  no-unused-vars: 'warn',
  import/prefer-default-export: 'warn'
}
