env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
plugins:
  - '@typescript-eslint'
settings:
  import/resolver:
    node:
      extensions: [".js", ".jsx", ".ts", ".tsx"]
rules: {
  linebreak-style: 'off',
  no-console: 'off',
  no-duplicate-imports: 'warn',
  import/extensions: ['error', 'never'],
  class-methods-use-this: 'off',
  no-unused-vars: 'off',
  import/prefer-default-export: 'warn',
  lines-between-class-members: 'off',
}
